# Generated by Django 5.1.6 on 2025-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvcndanhgia',
            name='trangthai',
            field=models.BooleanField(default=False),
        ),
    ]
