# Generated by Django 5.1.6 on 2025-06-03 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0002_gvcndanhgia_trangthai'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamDRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cham_drl', models.CharField(max_length=20, unique=True, verbose_name='Mã đợt chấm DRL')),
                ('ten_dot_cham', models.CharField(max_length=255, verbose_name='Tên đợt chấm DRL')),
                ('ngay_gio_bat_dau', models.DateTimeField(verbose_name='Ngày giờ bắt đầu chấm DRL')),
                ('ngay_gio_ket_thuc', models.DateTimeField(verbose_name='Ngày giờ kết thúc chấm DRL')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('isActive', models.BooleanField(default=False, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_dot_cham_drl', to='app_nckh9.hocky', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'Đợt chấm điểm rèn luyện',
                'verbose_name_plural': 'Danh sách đợt chấm điểm rèn luyện',
                'ordering': ['-created_at'],
            },
        ),
    ]
