# Generated by Django 5.1.6 on 2025-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0003_chamdrl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ythuc_hoctap', 'Ý thức và kết quả học tập'), ('ythuc_kyluat', 'Ý thức chấp hành nội quy, quy chế'), ('hoatdong_doanthethechao', 'Hoạt động đoàn thể, thể thao'), ('quanhe_congdong', 'Quan hệ cộng đồng'), ('phamchat_daoduc', 'Phẩm chất đạo đức'), ('phutrachlop', 'Phụ trách lớp, đoàn thể')], max_length=50, verbose_name='Mục đánh giá')),
                ('sub_section', models.CharField(max_length=255, verbose_name='Tiểu mục')),
                ('rule_name', models.CharField(max_length=500, verbose_name='Tên quy tắc')),
                ('point_type', models.CharField(choices=[('cong', 'Cộng điểm'), ('tru', 'Trừ điểm')], max_length=10, verbose_name='Loại điểm')),
                ('points', models.CharField(max_length=20, verbose_name='Số điểm')),
                ('max_points', models.IntegerField(default=0, verbose_name='Điểm tối đa')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Quy tắc chấm điểm',
                'verbose_name_plural': 'Quy tắc chấm điểm',
                'ordering': ['section', 'order'],
            },
        ),
    ]
